### ISSUE TITLE
Derive multiple tables from one resource

### ISSUE THREAD

**Issue by jonross** [jonross/kubeql#26]
e.g.
* `pods` and `containers` from `kubectl get pods`
* `nodes` and `taints` from `kubectl get nodes`

Closing, correction, this is already done.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added ContainersTable to extract container information from pods. Modified PodsTable to include container count. Updated NodeTaintsTable to extract taint information directly from nodes.

You can review changes in this commit: https://github.com/mnmnk43434/jonross-kubeql-26/commit/3e6fa6c881dc8067b6239caacf0ceab548c6a0d5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jonross** [comment]
This is already done
